# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @useDynLib hiperglm
#' @importFrom Rcpp sourceCpp
rcpp_qr <- function(A, b) {
    .Call('_hiperglm_rcpp_qr', PACKAGE = 'hiperglm', A, b)
}

